authors:
  christian-jennewein:
    name:     "Christian Jennewein"
    nickname: "Christian"
    twitter:  "cestcri"
    github:   "cestcri"
    role:     "Tech Manager"
  nicolas-schwartz:
    name:     "Nicolas Schwartz"
    nickname: "Nico"
    twitter:  "nicoschwartz"
    github:   "nicoschwartz"
    role:     "Tech Manager"
description:  "Share More, Learn More - BlaBlaCar's Tech team"
highlighter:  true
markdown:     rdiscount
name:         "BlaBlaTech Blog"
paginate:     10
permalink:    /archive/:year/:month/:day/:title
url:          "http://blablatech.com"